{% set name = "gradescope-utils" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradescope-utils-{{ version }}.tar.gz
  sha256: 51542455ab9f4c9f75612e0a4ee0cb0c1386809de41254a77d3fd7b6c09525d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gradescope_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gradescope/gradescope-utils
  summary: Utilities for building Gradescope autograders
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
